<h3 class="top">RTL871x Built-in Web server <sup>&copy;</sup></h3>
<div class="menu">
	<div>
		<a href="/index.htm">Main</a>
		<a href="/websock.htm">WebSocket</a>
		<a href="/protect/wifi.htm">WiFi settings</a>
		<a href="/protect/scan.htm">WiFi Scan</a>
		<a href="/protect3/upload.htm">WebFS Upload</a>
		<a href="/protect/setup.htm">System Setup</a>
	</div>
	<div>
		<a href="/protect/gpio.htm">GPIO</a>
		<a href="/protect2/hexdmpb.htm">HexDump Bytes</a>
		<a href="/protect2/hexdmpd.htm">HexDump DWord</a>
		<a href="/protect2/tstfuncs.htm">Download Bin</a>
		<a href="/protect2/dsleep.htm">Deep Sleep</a>
		<a href="/protect2/debug.htm">Debug and Test</a>
	</div>
</div>
<script type="text/javascript">
for (var i = 0; i < document.links.length; i++) {
    if (document.links[i].href == document.URL) {
        document.links[i].className = 'active';
    }
}
</script>